server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: localeMessages

#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"

