server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: digilog
      password: bistel01
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

