server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  messages:
    basename: localeMessages

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true

  # security policy change, so add follows
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"

